### ISSUE TITLE
tcl: crash on test shutdown

### ISSUE THREAD

**Issue by cznic** [cznic/sqlite2go#3]
TCL test suites cannot even start yet because of #2, but some individual test do pass. For example, all tests in `select1.test` are okay, it's just some bug in the shutdown code that crashes.

```
jnml@4670:~/src/tmp/tcl> ./tcl select1.test 
select1-1.1... Ok
select1-1.2... Ok
select1-1.3... Ok
select1-1.4... Ok
select1-1.5... Ok
select1-1.6... Ok
select1-1.7... Ok
select1-1.8... Ok
select1-1.8.1... Ok
select1-1.8.2... Ok
select1-1.8.3... Ok
select1-1.9... Ok
select1-1.9.1... Ok
select1-1.9.2... Ok
select1-1.10... Ok
select1-1.11... Ok
select1-1.11.1... Ok
select1-1.11.2... Ok
select1-1.12... Ok
select1-1.13... Ok
select1-2.0... Ok
select1-2.1... Ok
select1-2.2... Ok
select1-2.3... Ok
select1-2.4... Ok
select1-2.5... Ok
select1-2.5.1... Ok
select1-2.5.2... Ok
select1-2.5.3... Ok
select1-2.6... Ok
select1-2.7... Ok
select1-2.8... Ok
select1-2.8.1... Ok
select1-2.8.2... Ok
select1-2.8.3... Ok
select1-2.9... Ok
select1-2.10... Ok
select1-2.11... Ok
select1-2.12... Ok
select1-2.13... Ok
select1-2.13.1... Ok
select1-2.13.2... Ok
select1-2.14... Ok
select1-2.15... Ok
select1-2.16... Ok
select1-2.17... Ok
select1-2.17.1... Ok
select1-2.18... Ok
select1-2.19... Ok
select1-2.20... Ok
select1-2.21... Ok
select1-2.22... Ok
select1-2.23... Ok
select1-3.1... Ok
select1-3.2... Ok
select1-3.3... Ok
select1-3.4... Ok
select1-3.5... Ok
select1-3.6... Ok
select1-3.7... Ok
select1-3.8... Ok
select1-3.9... Ok
select1-4.1... Ok
select1-4.2... Ok
select1-4.3... Ok
select1-4.4... Ok
select1-4.5... Ok
select1-4.5... Ok
select1-4.6... Ok
select1-4.8... Ok
select1-4.9.1... Ok
select1-4.9.2... Ok
select1-4.10.1... Ok
select1-4.10.2... Ok
select1-4.11... Ok
select1-4.12... Ok
select1-4.13... Ok
select1-5.1... Ok
select1-6.1... Ok
select1-6.1.1... Ok
select1-6.1.2... Ok
select1-6.1.3... Ok
select1-6.1.4... Ok
select1-6.1.5... Ok
select1-6.1.6... Ok
select1-6.2... Ok
select1-6.3... Ok
select1-6.3.1... Ok
select1-6.4... Ok
select1-6.4a... Ok
select1-6.5... Ok
select1-6.5.1... Ok
select1-6.6... Ok
select1-6.7... Ok
select1-6.8... Ok
select1-6.8b... Ok
select1-6.8c... Ok
select1-6.9.1... Ok
select1-6.9.2... Ok
select1-6.9.3... Ok
select1-6.9.4... Ok
select1-6.9.5... Ok
select1-6.9.6... Ok
select1-6.9.7... Ok
select1-6.9.8... Ok
select1-6.9.9... Ok
select1-6.9.10... Ok
select1-6.9.11... Ok
select1-6.9.12... Ok
select1-6.9.13... Ok
select1-6.9.14... Ok
select1-6.9.15... Ok
select1-6.9.16... Ok
select1-6.10... Ok
select1-6.11... Ok
select1-6.20... Ok
select1-6.21... Ok
select1-6.22... Ok
select1-6.23... Ok
select1-7.1... Ok
select1-7.2... Ok
select1-7.3... Ok
select1-7.4... Ok
select1-7.5... Ok
select1-7.6... Ok
select1-7.7... Ok
select1-7.8... Ok
select1-7.9... Ok
select1-8.1... Ok
select1-8.2... Ok
select1-8.3... Ok
select1-8.5... Ok
select1-9.2... Ok
select1-9.3... Ok
select1-9.4... Ok
select1-9.5... Ok
select1-10.1... Ok
select1-10.2... Ok
select1-10.3... Ok
select1-10.4... Ok
select1-10.5... Ok
select1-10.6... Ok
select1-10.7... Ok
select1-11.1... Ok
select1-11.2.1... Ok
select1-11.2.2... Ok
select1-11.4.1... Ok
select1-11.4.2... Ok
select1-11.5.1... Ok
select1-11.6... Ok
select1-11.7... Ok
select1-11.8... Ok
select1-11.9... Ok
select1-11.10... Ok
select1-11.11... Ok
select1-11.12... Ok
select1-11.13... Ok
select1-11.14... Ok
select1-11.15... Ok
select1-11.16... Ok
select1-12.1... Ok
select1-12.2... Ok
select1-12.3... Ok
select1-12.4... Ok
select1-12.5... Ok
select1-12.6... Ok
select1-12.7... Ok
select1-12.8... Ok
select1-12.9... Ok
select1-12.10... Ok
select1-13.1... Ok
select1-14.1... Ok
select1-14.2... Ok
select1-15.1... Ok
select1-15.2... Ok
select1-15.3... Ok
select1-16.1... Ok
select1-16.2... Ok
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x640 pc=0x9f9ed0]

goroutine 1 [running]:
main._4740resetAutoExtObjCmd(0x7fd329c001d0, 0x0, 0x7fd328f00020, 0x7fd300000001, 0x7fd328e00870, 0x7fd300000000)
	/home/jnml/src/tmp/tcl/test_autoext.go:85 +0x30
main._2955Dispatch(0x7fd329c001d0, 0x7fd3291401d8, 0x7fd328f00020, 0x7fd300000000, 0x7fd300000000)
	/home/jnml/src/tmp/tcl/tclBasic.go:3150 +0x6d
main.XTclNRRunCallbacks(0x7fd329c001d0, 0x7fd328f00020, 0x0, 0x0, 0x7fd300200010)
	/home/jnml/src/tmp/tcl/tclBasic.go:2032 +0x78
main.XTcl_EvalObjv(0x7fd329c001d0, 0x7fd328f00020, 0x7fd300000005, 0x7fd328e00300, 0x7fd300200010, 0x5)
	/home/jnml/src/tmp/tcl/tclBasic.go:1829 +0x9e
main.XTclEvalEx(0x7fd329c001d0, 0x7fd328f00020, 0xe31346, 0x1ae, 0xc400000001, 0x0, 0xe31346, 0x0)
	/home/jnml/src/tmp/tcl/tclBasic.go:1599 +0x106c
main.XTcl_EvalEx(0x7fd329c001d0, 0x7fd328f00020, 0xe31346, 0xffffffff, 0xc4200a1e50)
	/home/jnml/src/tmp/tcl/tclBasic.go:3769 +0x65
main.XTcl_Eval(0x7fd329c001d0, 0x7fd328f00020, 0xe31346, 0x0)
	/home/jnml/src/tmp/tcl/tclBasic.go:10255 +0x49
main.XTcl_GlobalEval(0x7fd329c001d0, 0x7fd328f00020, 0xe31346, 0x0)
	/home/jnml/src/tmp/tcl/tclBasic.go:10974 +0x60
main.Xmain(0x7fd329c001d0, 0x2, 0x7fd329e00020, 0x7fd300000000)
	/home/jnml/src/tmp/tcl/tclsqlite.go:5158 +0x38f
main.X_start(0x7fd329c001d0, 0x2, 0x7fd329e00020)
	/home/jnml/src/tmp/tcl/tclsqlite.go:5103 +0x82
main.main()
	/home/jnml/src/tmp/tcl/tclsqlite.go:10412 +0x17f
jnml@4670:~/src/tmp/tcl> 
```

**Comment by cznic** [comment]
Updates cznic/sqlite3shell#4.

**Comment by cznic** [comment]
With https://github.com/cznic/sqlite2go/commit/fb06ba8698e9ffe3ea203d2c2025272cbcae0f63

```
jnml@r550:~/src/tmp/test> rm -f ./test
jnml@r550:~/src/tmp/test> go build
jnml@r550:~/src/tmp/test> ./test select1.test 
select1-1.1... Ok
select1-1.2... Ok
select1-1.3... Ok
select1-1.4... Ok
select1-1.5... Ok
select1-1.6... Ok
select1-1.7... Ok
select1-1.8... Ok
select1-1.8.1... Ok
select1-1.8.2... Ok
select1-1.8.3... Ok
select1-1.9... Ok
select1-1.9.1... Ok
select1-1.9.2... Ok
select1-1.10... Ok
select1-1.11... Ok
select1-1.11.1... Ok
select1-1.11.2... Ok
select1-1.12... Ok
select1-1.13... Ok
select1-2.0... Ok
select1-2.1... Ok
select1-2.2... Ok
select1-2.3... Ok
select1-2.4... Ok
select1-2.5... Ok
select1-2.5.1... Ok
select1-2.5.2... Ok
select1-2.5.3... Ok
select1-2.6... Ok
select1-2.7... Ok
select1-2.8... Ok
select1-2.8.1... Ok
select1-2.8.2... Ok
select1-2.8.3... Ok
select1-2.9... Ok
select1-2.10... Ok
select1-2.11... Ok
select1-2.12... Ok
select1-2.13... Ok
select1-2.13.1... Ok
select1-2.13.2... Ok
select1-2.14... Ok
select1-2.15... Ok
select1-2.16... Ok
select1-2.17... Ok
select1-2.17.1... Ok
select1-2.18... Ok
select1-2.19... Ok
select1-2.20... Ok
select1-2.21... Ok
select1-2.22... Ok
select1-2.23... Ok
select1-3.1... Ok
select1-3.2... Ok
select1-3.3... Ok
select1-3.4... Ok
select1-3.5... Ok
select1-3.6... Ok
select1-3.7... Ok
select1-3.8... Ok
select1-3.9... Ok
select1-4.1... Ok
select1-4.2... Ok
select1-4.3... Ok
select1-4.4... Ok
select1-4.5... Ok
select1-4.5... Ok
select1-4.6... Ok
select1-4.8... Ok
select1-4.9.1... Ok
select1-4.9.2... Ok
select1-4.10.1... Ok
select1-4.10.2... Ok
select1-4.11... Ok
select1-4.12... Ok
select1-4.13... Ok
select1-5.1... Ok
select1-6.1... Ok
select1-6.1.1... Ok
select1-6.1.2... Ok
select1-6.1.3... Ok
select1-6.1.4... Ok
select1-6.1.5... Ok
select1-6.1.6... Ok
select1-6.2... Ok
select1-6.3... Ok
select1-6.3.1... Ok
select1-6.4... Ok
select1-6.4a... Ok
select1-6.5... Ok
select1-6.5.1... Ok
select1-6.6... Ok
select1-6.7... Ok
select1-6.8... Ok
select1-6.8b... Ok
select1-6.8c... Ok
select1-6.9.1... Ok
select1-6.9.2... Ok
select1-6.9.3... Ok
select1-6.9.4... Ok
select1-6.9.5... Ok
select1-6.9.6... Ok
select1-6.9.7... Ok
select1-6.9.8... Ok
select1-6.9.9... Ok
select1-6.9.10... Ok
select1-6.9.11... Ok
select1-6.9.12... Ok
select1-6.9.13... Ok
select1-6.9.14... Ok
select1-6.9.15... Ok
select1-6.9.16... Ok
select1-6.10... Ok
select1-6.11... Ok
select1-6.20... Ok
select1-6.21... Ok
select1-6.22... Ok
select1-6.23... Ok
select1-7.1... Ok
select1-7.2... Ok
select1-7.3... Ok
select1-7.4... Ok
select1-7.5... Ok
select1-7.6... Ok
select1-7.7... Ok
select1-7.8... Ok
select1-7.9... Ok
select1-8.1... Ok
select1-8.2... Ok
select1-8.3... Ok
select1-8.5... Ok
select1-9.2... Ok
select1-9.3... Ok
select1-9.4... Ok
select1-9.5... Ok
select1-10.1... Ok
select1-10.2... Ok
select1-10.3... Ok
select1-10.4... Ok
select1-10.5... Ok
select1-10.6... Ok
select1-10.7... Ok
select1-11.1... Ok
select1-11.2.1... Ok
select1-11.2.2... Ok
select1-11.4.1... Ok
select1-11.4.2... Ok
select1-11.5.1... Ok
select1-11.6... Ok
select1-11.7... Ok
select1-11.8... Ok
select1-11.9... Ok
select1-11.10... Ok
select1-11.11... Ok
select1-11.12... Ok
select1-11.13... Ok
select1-11.14... Ok
select1-11.15... Ok
select1-11.16... Ok
select1-12.1... Ok
select1-12.2... Ok
select1-12.3... Ok
select1-12.4... Ok
select1-12.5... Ok
select1-12.6... Ok
select1-12.7... Ok
select1-12.8... Ok
select1-12.9... Ok
select1-12.10... Ok
select1-13.1... Ok
select1-14.1... Ok
select1-14.2... Ok
select1-15.1... Ok
select1-15.2... Ok
select1-15.3... Ok
select1-16.1... Ok
select1-16.2... Ok
SQLite 2017-10-24 18:55:49 1a584e499906b5c87ec7d43d4abce641fdf017c42125b083109bc77c4de48827
0 errors out of 179 tests on  Linux 64-bit little-endian
All memory allocations freed - no leaks
Memory used:          now 0  max 478160  max-size 120000
Allocation count:     now 0  max 427
Page-cache used:      now 0  max 0  max-size 4096
Page-cache overflow:  now 0  max 20480
Maximum memory usage: 478160 bytes
Current memory usage: 0 bytes
Number of malloc()  : -1 calls
jnml@r550:~/src/tmp/test> 
```
