### ISSUE TITLE
tcl: all.test does cannot yet run properly

### ISSUE THREAD

**Issue by cznic** [cznic/sqlite2go#4]
Progress tracking issue.

With https://github.com/cznic/crt/commit/7f3ccc4da65a7586054bb21d694f260e5d5642e2 and https://github.com/cznic/sqlite2go/commit/905a389e6d7f8df3b9da9c75d48faeb9b211f78b

```
jnml@4670:~/src/tmp/tcl> ./tcl all.test
8_3_names.test-closeallfiles... Ok
8_3_names.test-sharedcachesetting... Ok
Time: 8_3_names.test 18 ms
panic: TODO

goroutine 1 [running]:
github.com/cznic/crt.Xstrtoul(0x7f5e649001d0, 0x7f5e64d85b65, 0x7f5e64176040, 0xc40000000a, 0x4ba462)
	/home/jnml/src/github.com/cznic/crt/stdlib_linux.go:23 +0x39
main.XTcl_AppendFormatToObj(0x7f5e649001d0, 0x7f5e5eb00020, 0x7f5e5edd87a0, 0x7f5e64d85b65, 0xc400000003, 0x7f5e5ea00bc0, 0x0)
	/home/jnml/src/tmp/tcl/tclStringObj.go:1029 +0x30e3
main.XTcl_Format(0x7f5e649001d0, 0x7f5e5eb00020, 0x7f5e64d85b60, 0x3, 0x7f5e5ea00bc0, 0xc4200f6120)
	/home/jnml/src/tmp/tcl/tclStringObj.go:3323 +0x72
main.XTcl_FormatObjCmd(0x7f5e649001d0, 0x0, 0x7f5e5eb00020, 0x7f5e00000005, 0x7f5e5ea00bb0, 0x7f5e00000000)
	/home/jnml/src/tmp/tcl/tclCmdAH.go:5724 +0x77
main._2955Dispatch(0x7f5e649001d0, 0x7f5e5edcefe8, 0x7f5e5eb00020, 0x7f5e00000000, 0x7f5e00000000)
	/home/jnml/src/tmp/tcl/tclBasic.go:3154 +0x6d
main.XTclNRRunCallbacks(0x7f5e649001d0, 0x7f5e5eb00020, 0x0, 0x0, 0x7f5e00200010)
	/home/jnml/src/tmp/tcl/tclBasic.go:2035 +0x78
main.XTcl_EvalObjv(0x7f5e649001d0, 0x7f5e5eb00020, 0x7f5e00000005, 0x7f5e5ea00300, 0x7f5e00200010, 0x5)
	/home/jnml/src/tmp/tcl/tclBasic.go:1832 +0x9e
main.XTclEvalEx(0x7f5e649001d0, 0x7f5e5eb00020, 0xea7346, 0x1ae, 0xc400000001, 0x0, 0xea7346, 0x0)
	/home/jnml/src/tmp/tcl/tclBasic.go:1599 +0x106c
main.XTcl_EvalEx(0x7f5e649001d0, 0x7f5e5eb00020, 0xea7346, 0xffffffff, 0xc4200b5e50)
	/home/jnml/src/tmp/tcl/tclBasic.go:3773 +0x65
main.XTcl_Eval(0x7f5e649001d0, 0x7f5e5eb00020, 0xea7346, 0x0)
	/home/jnml/src/tmp/tcl/tclBasic.go:10264 +0x49
main.XTcl_GlobalEval(0x7f5e649001d0, 0x7f5e5eb00020, 0xea7346, 0x0)
	/home/jnml/src/tmp/tcl/tclBasic.go:10983 +0x60
main.Xmain(0x7f5e649001d0, 0x2, 0x7f5e64b00020, 0x7f5e00000000)
	/home/jnml/src/tmp/tcl/tclsqlite.go:5158 +0x38f
main.X_start(0x7f5e649001d0, 0x2, 0x7f5e64b00020)
	/home/jnml/src/tmp/tcl/tclsqlite.go:5103 +0x82
main.main()
	/home/jnml/src/tmp/tcl/tclsqlite.go:10418 +0x17f
jnml@4670:~/src/tmp/tcl> 
```

**Comment by cznic** [comment]
With https://github.com/cznic/sqlite2go/commit/fb06ba8698e9ffe3ea203d2c2025272cbcae0f63

```
--- FAIL: TestTCL (2305.78s)
	all_test.go:1358: 
		Test cases:   239474
		Pass:         238476 (99.58%)
		Fail:            998 (0.42%)
		! alter-7.1 expected: [text 1 integer -2 text 5.4e-8 real 5.4e-8]
		! alter-7.1 got:      [text 1 integer -2 text 5.4e-8 real {}]
		! attach-8.1 expected: [1 {file is not a database}]
		! attach-8.1 got:      [1 {unable to open database: test2.db}]
		! attach-8.2 expected: [26]
		! attach-8.2 got:      [14]
		! auth3-2.2 expected: [1]
		! auth3-2.2 got:      [0]
		! autovacuum-1.1.3 expected: [4]
		! autovacuum-1.1.3 got:      [16]
		... too many fails
	all_test.go:1366: 
		Test binary exit error: exit status 1
		Last completed test file: "Time: selectC.test 266 ms"
		Last passed test: "no_optimization.selectC-5.3... Ok"
		Last line written to stdout: "Page-cache overflow:  now 0  max 21057216"
		Blacklisted test files: 113
		btreefault.test
                ...
		whereD.test
```

**Comment by cznic** [comment]
@steffengy I think it's now probably a good time to merge branch `tcl` into `master` (the same for cznic/crt). Before doing that I would like to know if there are any objections and/or if it would disrupt something on your side. Please let me know, thank you.

In any case, more than 200k TCL test cases do pass. 998 test case fails and 113 test file crashes to resolve and fix, but I think there's maybe a light at the end of the tunnel ;-)

**Comment by steffengy** [comment]
sure, we do not want huge diffs, so basing the windows port on that is desirable.
Not sure when I'll get around to actually continue work on it, but hopefully soonish.

**Comment by cznic** [comment]
Thanks for the info. Wrt to not enough free time: No worries, the cznic/sqlite project, which is the final target, is in progress for about a year already, IINM. Your contributions will be appreciated at any time int the future ;-)

**Comment by cznic** [comment]
With https://github.com/cznic/sqlite2go/commit/032b37a471adb68dbf9cdeb40cc1095992a35374

```
--- FAIL: TestTCL (3241.93s)
        all_test.go:1354: 
                Test cases:   260473
                Pass:         259499 (99.63%)
                Fail:            974 (0.37%)
                ! alter-7.1 expected: [text 1 integer -2 text 5.4e-8 real 5.4e-8]
                ! alter-7.1 got:      [text 1 integer -2 text 5.4e-8 real {}]
                ! attach-8.1 expected: [1 {file is not a database}]
                ! attach-8.1 got:      [1 {unable to open database: test2.db}]
                ! attach-8.2 expected: [26]
                ! attach-8.2 got:      [14]
                ! auth3-2.2 expected: [1]
                ! auth3-2.2 got:      [0]
                ! autovacuum-1.1.3 expected: [4]
                ! autovacuum-1.1.3 got:      [16]
                ... too many fails
        all_test.go:1362: 
                Test binary exit error: exit status 1
                Last completed test file: "Time: selectC.test 199 ms"
                Last passed test: "no_optimization.selectC-5.3... Ok"
                Last line written to stdout: "Page-cache overflow:  now 0  max 21057216"
                Blacklisted test files: 107
                btreefault.test
                ...
                writecrash.test
```

**Comment by cznic** [comment]
https://github.com/cznic/sqlite2go/commit/fb06ba8698e9ffe3ea203d2c2025272cbcae0f63 (Apr 10 10:43:30 2018) + https://github.com/cznic/crt/commit/1a70c48f68a598e90d8ed1460e06cc3c74b29610

```
--- FAIL: TestTCL (2826.59s)
	all_test.go:1366: 
		Test cases:   239415
		Pass:         238475 (99.61%)
		Fail:            940 (0.39%)
		! alter-7.1 expected: [text 1 integer -2 text 5.4e-8 real 5.4e-8]
		! alter-7.1 got:      [text 1 integer -2 text 5.4e-8 real {}]
		! attach-8.1 expected: [1 {file is not a database}]
		! attach-8.1 got:      [1 {unable to open database: test2.db}]
		! attach-8.2 expected: [26]
		! attach-8.2 got:      [14]
		! auth3-2.2 expected: [1]
		! auth3-2.2 got:      [0]
		! autovacuum-1.1.3 expected: [4]
		! autovacuum-1.1.3 got:      [16]
		... too many fails
	all_test.go:1374: 
		Test binary exit error: exit status 1
		Last completed test file: "Time: selectC.test 238 ms"
		Last passed test: "no_optimization.selectC-5.3... Ok"
		Last line written to stdout: "Page-cache overflow:  now 0  max 21057216"
		Blacklisted test files: 113
		btreefault.test
                ...
		writecrash.test
FAIL
FAIL	github.com/cznic/sqlite2go/internal/ccgo	2826.630s
```

**Comment by cznic** [comment]
With https://github.com/cznic/sqlite2go/commit/032b37a471adb68dbf9cdeb40cc1095992a35374 (Apr 12 13:34:29 2018 +0200) + https://github.com/cznic/crt/commit/abb3194cd8c7546eda466c73d1ef0ba82efbc549 (Apr 11 17:55:52 2018 +0200)

```
--- FAIL: TestTCL (3279.01s)
	all_test.go:1354: 
		Test cases:   260473
		Pass:         259499 (99.63%)
		Fail:            974 (0.37%)
		! alter-7.1 expected: [text 1 integer -2 text 5.4e-8 real 5.4e-8]
		! alter-7.1 got:      [text 1 integer -2 text 5.4e-8 real {}]
		! attach-8.1 expected: [1 {file is not a database}]
		! attach-8.1 got:      [1 {unable to open database: test2.db}]
		! attach-8.2 expected: [26]
		! attach-8.2 got:      [14]
		! auth3-2.2 expected: [1]
		! auth3-2.2 got:      [0]
		! autovacuum-1.1.3 expected: [4]
		! autovacuum-1.1.3 got:      [16]
		... too many fails
	all_test.go:1362: 
		Test binary exit error: exit status 1
		Last completed test file: "Time: selectC.test 1214 ms"
		Last passed test: "no_optimization.selectC-5.3... Ok"
		Last line written to stdout: "Page-cache overflow:  now 0  max 21057216"
		Blacklisted test files: 107
		btreefault.test
                ...
		writecrash.test
FAIL
FAIL	github.com/cznic/sqlite2go/internal/ccgo	3279.036s
```

**Comment by cznic** [comment]
With https://github.com/cznic/sqlite2go/commit/032b37a471adb68dbf9cdeb40cc1095992a35374 (Apr 12 13:34:29 2018 +0200) + https://github.com/cznic/crt/commit/b510cbb235358957ae3446266e219cb184743b8c (Apr 25 17:51:13 2018 +0200)

```
--- FAIL: TestTCL (4556.11s)
	all_test.go:1354: 
		Test cases:   259820
		Pass:         258820 (99.62%)
		Fail:           1000 (0.38%)
		! alter-7.1 expected: [text 1 integer -2 text 5.4e-8 real 5.4e-8]
		! alter-7.1 got:      [text 1 integer -2 text 5.4e-8 real {}]
		! attach-8.1 expected: [1 {file is not a database}]
		! attach-8.1 got:      [1 {unable to open database: test2.db}]
		! attach-8.2 expected: [26]
		! attach-8.2 got:      [14]
		! auth3-2.2 expected: [1]
		! auth3-2.2 got:      [0]
		! autovacuum-1.1.3 expected: [4]
		! autovacuum-1.1.3 got:      [16]
		... too many fails
	all_test.go:1362: 
		Test binary exit error: exit status 1
		Last completed test file: "Time: without_rowid2.test 230 ms"
		Last passed test: "without_rowid3-15.1.5... Ok"
		Last line written to stdout: "Number of malloc()  : -1 calls"
		Blacklisted test files: 107
		btreefault.test
		...
		writecrash.test
FAIL
exit status 1
FAIL	github.com/cznic/sqlite2go/internal/ccgo	4556.141s
```

**Comment by cznic** [comment]
With https://github.com/cznic/sqlite2go/commit/032b37a471adb68dbf9cdeb40cc1095992a35374 (Apr 12 13:34:29 2018 +0200) + https://github.com/cznic/crt/commit/785cf13596fbb06c19be348def853734656a0ae8 (Apr 26 17:56:02 2018 +0200)

```
--- FAIL: TestTCL (4406.44s)
	all_test.go:1354: 
		Test cases:   260880
		Pass:         259911 (99.63%)
		Fail:            969 (0.37%)
		! alter-7.1 expected: [text 1 integer -2 text 5.4e-8 real 5.4e-8]
		! alter-7.1 got:      [text 1 integer -2 text 5.4e-8 real {}]
		! attach-8.1 expected: [1 {file is not a database}]
		! attach-8.1 got:      [1 {unable to open database: test2.db}]
		! attach-8.2 expected: [26]
		! attach-8.2 got:      [14]
		! auth3-2.2 expected: [1]
		! auth3-2.2 got:      [0]
		! autovacuum-1.1.3 expected: [4]
		! autovacuum-1.1.3 got:      [16]
		... too many fails
	all_test.go:1362: 
		Test binary exit error: exit status 1
		Last completed test file: "Time: selectC.test 377 ms"
		Last passed test: "no_optimization.selectC-5.3... Ok"
		Last line written to stdout: "Page-cache overflow:  now 0  max 21057216"
		Blacklisted test files: 107
		btreefault.test
		...
		writecrash.test
FAIL
exit status 1
FAIL	github.com/cznic/sqlite2go/internal/ccgo	4406.464s
```

**Comment by cznic** [comment]
With https://github.com/cznic/sqlite2go/commit/032b37a471adb68dbf9cdeb40cc1095992a35374 (Apr 12 13:34:29 2018 +0200) + https://github.com/cznic/crt/commit/7762ce92d73e338bd33f4bc5017480a9cffa0725 (Apr 26 17:56:02 2018 +0200)

```
--- FAIL: TestTCL (4504.38s)
	all_test.go:1354: 
		Test cases:   260197
		Pass:         259197 (99.62%)
		Fail:           1000 (0.38%)
		! alter-7.1 expected: [text 1 integer -2 text 5.4e-8 real 5.4e-8]
		! alter-7.1 got:      [text 1 integer -2 text 5.4e-8 real {}]
		! attach-8.1 expected: [1 {file is not a database}]
		! attach-8.1 got:      [1 {unable to open database: test2.db}]
		! attach-8.2 expected: [26]
		! attach-8.2 got:      [14]
		! auth3-2.2 expected: [1]
		! auth3-2.2 got:      [0]
		! autovacuum-1.1.3 expected: [4]
		! autovacuum-1.1.3 got:      [16]
		... too many fails
	all_test.go:1362: 
		Test binary exit error: exit status 1
		Last completed test file: "Time: without_rowid6.test 1439 ms"
		Last passed test: "without_rowid6-600... Ok"
		Last line written to stdout: "Number of malloc()  : -1 calls"
		Blacklisted test files: 107
		btreefault.test
		...
		writecrash.test
FAIL
exit status 1
FAIL	github.com/cznic/sqlite2go/internal/ccgo	4504.407s
```

**Comment by cznic** [comment]
With https://github.com/cznic/sqlite2go/commit/032b37a471adb68dbf9cdeb40cc1095992a35374 (Apr 12 13:34:29 2018 +0200) + https://github.com/cznic/crt/commit/74da70b206b5d84367f64439cd2c92313b09662c (Apr 29 20:19:03 2018 +0200)

```
--- FAIL: TestTCL (1070.78s)
	all_test.go:1354: 
		Test cases:    56589
		Pass:          56219 (99.35%)
		Fail:            370 (0.65%)
		! alter-7.1 expected: [text 1 integer -2 text 5.4e-8 real 5.4e-8]
		! alter-7.1 got:      [text 1 integer -2 text 5.4e-8 real {}]
		! alter2-1.3 expected: [1 2 {} 3 4 {} 5 6 {}]
		! alter2-1.3 got:      [1 2 3 4 5 6]
		Error: no such column: c
		Error: no such column: c
		Error: no such column: c
		Error: no such column: c
		Error: no such column: c
		Error: no such column: d
		... too many fails
	all_test.go:1362: 
		Test binary exit error: exit status 2
		Last completed test file: "Time: expr.test 1432 ms"
		Last passed test: "extension01-1.1... Ok"
		Last line written to stdout: "extension01-1.2..."
		Blacklisted test files: 107
		btreefault.test
		...
		writecrash.test
FAIL
exit status 1
FAIL	github.com/cznic/sqlite2go/internal/ccgo	1070.820s
```
