### ISSUE TITLE
cpp failure: cpp-expand/9.c

### ISSUE THREAD

**Issue by cznic** [cznic/sqlite2go#8]
Tracking issue: Fix failure of the test case introduced in https://github.com/cznic/sqlite2go/commit/009e2de130daf943a72d3af25a131bf0530731f6 of #7.

**Comment by cznic** [comment]
@steffengy First look into this:

```
jnml@4670:~/src/github.com/cznic/sqlite2go/internal/c99> gcc -o /dev/null testdata/cpp-expand/9.c 
testdata/cpp-expand/9.c:3:15: warning: initializer element is not a constant expression [enabled by default]
 #define TEST3 (TEST42 >= 0x0502 || !defined (TESTBASE))
               ^
testdata/cpp-expand/9.c:8:12: note: in expansion of macro ‘TEST3’
 int TEST = TEST3;
            ^
jnml@4670:~/src/github.com/cznic/sqlite2go/internal/c99> 
```

I think the problem is that after expansion, `defined` does not appear in a preprocessing directive while not being defined to be something else than a preprocesor magic pseudo function.

`cpp` seems to agree

```
jnml@4670:~/src/github.com/cznic/sqlite2go/internal/c99> cpp testdata/cpp-expand/9.c 
# 1 "testdata/cpp-expand/9.c"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 1 "<command-line>" 2
# 1 "testdata/cpp-expand/9.c"







int TEST = (0x0502 >= 0x0502 || !defined (1));

int main (void) {
 return 0;
}
jnml@4670:~/src/github.com/cznic/sqlite2go/internal/c99> 
```

This does not look like a bug in c99/cpp.go to me. WDYT?

**Comment by cznic** [comment]
OTOH, the lhs of the `||` operator is statically non-zero, so maybe the front-end should just ignore the rhs? Not sure if that's ok when the rhs is otherwise invalid. GCC does not like that definitely, so maybe we should not either, and that's the current situation.

**Comment by steffengy** [comment]
Yeap, I think I messed up the testcase. Sorry :(

Can you replace it with (this compiles with GCC without warnings):
```c
#define TEST42 0x0502
#define TESTBASE 1
#define TEST3 (TEST42 >= 0x0502 || !defined (TESTBASE))
#define TEST4

#if TEST3 && defined (TEST4)
    int test = 4;
#endif


int main (void) {
	return test;
}
```

which also yields:
```
--- FAIL: TestCPPExpand (0.00s)
panic: c99.TypeKind [recovered]
        panic: c99.TypeKind

goroutine 18 [running]:
testing.tRunner.func1(0xc04220e2d0)
        C:/Go/src/testing/testing.go:742 +0x2a4
panic(0x623180, 0xc0421ccc10)
        C:/Go/src/runtime/panic.go:505 +0x237
github.com/cznic/sqlite2go/internal/c99.checkFn(0xc04220c080, 0x6b8c20, 0xc042068848, 0xc04207d7a0)
        D:/projects/Go/gopath/src/github.com/cznic/sqlite2go/internal/c99/ast2.go:1535 +0x29a
github.com/cznic/sqlite2go/internal/c99.(*Expr).eval(0xc0420c4620, 0xc04220c080, 0xc0420c4701, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
```
